server:
  port: 8181

spring:
  datasource:
    username: ENC(q6LLZbftMmjGDK0f1mvxiw==)
    password: ENC(s5vuw9MMlxTbBNXMKrn4R6LeqvffC0zb)
#    q/5z11DqLs07obgaBENduHYyZNO06l69DuP9NQmhzldUjZaoh5FVjn8JYtnDemQlYYwx7F6bsJ4QLjz5WW4jhyxlHyOsFo2h2OjiYgeIU2PGZ8pyz7Lr7Z37iXZkz46bB/g5u/9zbvAWDgoSP4vl2u1+p8cA5yLPN36BeDoMOQf8p9TF33u2lhs7RfJgt5Ar0ceV6aM+04gudDi2+q2XIA
    url: jdbc:mysql://139.224.62.56:3306/students?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: 139.224.62.56
      port: 27017
      username: ENC(ciK8dIB5sEyN8R2UsdZzwg==)
      password: ENC(osqhwMkfjjVrBPcYNoEjkncEi0ssKdNL)
      authentication-database: admin
      database: students


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# jasypt加密的盐值
jasypt:
  encryptor:
    password: erp
